services:
  db:
    image: postgres:16
    container_name: nt_postgres
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - nt_pg_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: nt_pgadmin
    depends_on:
      db:
        condition: service_healthy
    env_file: ./.env
    ports:
      - "5050:80"
    volumes:
      - nt_pgadmin:/var/lib/pgadmin

  backend:
    container_name: nt_backend
    build:
      context: ./server
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - "8000:8000"
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  nt_pg_data:
  nt_pgadmin:
